### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by niftylettuce** [NetOxygen/node-qrcodeine#2]
``` log
λ ~/Public/myproject/ feature/qr-js-fix* npm install --save qrcodeine                                                        ∞
-
> qrcodeine@1.0.0 install /Users/someuser/Public/myproject/node_modules/qrcodeine
> node-gyp rebuild

  CXX(target) Release/obj.target/qrcodeine/src/qrcodeine.o
../src/qrcodeine.cc:11:10: fatal error: 'qrencode.h' file not found
#include <qrencode.h>
         ^
1 error generated.
make: *** [Release/obj.target/qrcodeine/src/qrcodeine.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/someuser/Public/myproject/node_modules/qrcodeine
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "qrcodeine"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! qrcodeine@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the qrcodeine@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the qrcodeine package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls qrcodeine
npm ERR! There is likely additional logging output above.
```

**Comment by niftylettuce** [comment]
Nevermind, I had to `brew install libpng libqrencode` first...
